language: r
pandoc_version: 1.17.2
cache: packages

before_install:
  - tlmgr install eulervm
  - tlmgr install fancyhdr
  - tlmgr install bera

before_script:
  - chmod +x ./_deploy.sh

script:
  - Rscript -e "bookdown::render_book('index.Rmd', output_format='all')"
  - cd ./latex/
  - pdflatex ./cover.tex
  - pdflatex ./merge.tex
  - cd ..
  - mv ./latex/merge.pdf _book/rmcdbook.pdf
  - ./_deploy.sh
